
"use client";

import { useLanguage } from '@/context/language-context';
import { Target, Microscope, BrainCircuit, Dna, FileText, Handshake, Rocket } from 'lucide-react';
import { Button } from '@/components/ui/button';
import Link from 'next/link';
import Image from 'next/image';

const translations = {
  en: {
    title: "The BugMed Labs Investment Deck",
    subtitle: "De-risking Drug Discovery with Generative AI",
    
    slide1_title: "The Mission: A New Paradigm for Therapeutics",
    slide1_text: "To build the world’s most efficient, data-driven therapeutic discovery engine, turning computational insights into life-saving medicines.",
    
    slide2_title: "The Problem: The Valley of Death in Drug Discovery",
    slide2_point1: "Massive Cost & Time: Billions of dollars and over a decade per drug, with a >90% failure rate.",
    slide2_point2: "Hypothesis Bottleneck: The primary failure point isn't just clinical trials; it's the initial, often flawed, biological hypothesis.",
    slide2_point3: "Data Overload, Insight Deficit: Massive biological datasets exist, but their complexity obscures novel therapeutic pathways.",

    slide3_title: "Our Solution: A Hypothesis Generation Engine",
    slide3_text1: "We don't just screen data; we create knowledge. Our proprietary AI platform ingests complex, multi-modal biological data (genomics, proteomics, clinical data) to identify scientific gaps and generate novel, testable, and data-driven therapeutic hypotheses.",
    slide3_text2: "We deliver de-risked, high-value assets before a single experiment is run in a lab.",

    slide4_title: "The Technology: How It Works",
    slide4_step1_title: "1. Data Integration & Knowledge Graph",
    slide4_step1_text: "We unify vast, siloed datasets into a proprietary biological knowledge graph, mapping complex relationships between genes, proteins, diseases, and compounds.",
    slide4_step2_title: "2. AI-Powered Gap Analysis",
    slide4_step2_text: "Our models traverse this graph to identify 'white spaces'—uncharted territories and non-obvious connections that represent untapped therapeutic opportunities.",
    slide4_step3_title: "3. Generative Hypothesis & Asset Creation",
    slide4_step3_text: "The engine formulates a complete therapeutic hypothesis, including mechanism of action, target validation, and initial asset design. This becomes a digital, pre-validated asset.",

    slide5_title: "Core Asset Example: A System for Targeted Modulation of Hostile Tissue Microenvironments",
    slide5_text: "Our platform generated a complete, patent-pending system to precisely alter hostile tissue microenvironments. This has profound implications for treating chronic and autoimmune diseases, representing a de-risked, high-value program ready for partnership.",
    slide5_link: "View Case Study",

    slide6_title: "Our Business Model: Capital-Efficient, High-Value Biotech",
    slide6_point1_title: "AI-Generated IP",
    slide6_point1_text: "We create and patent novel therapeutic assets generated by our platform.",
    slide6_point2_title: "Strategic Partnerships",
    slide6_point2_text: "We partner with leading pharmaceutical companies and venture builders to co-develop our assets, sharing risk and reward.",
    slide6_point3_title: "Platform as a Service",
    slide6_point3_text: "Future opportunities to license our platform to major pharma for their internal R&D pipelines.",

    slide7_title: "The Opportunity: Join Us in Building the Future",
    slide7_text: "We are seeking seed-stage investment to perform in-vitro validation for our lead AI-generated assets. This will convert our high-value digital discoveries into lab-validated intellectual property, ready for major out-licensing or co-development deals.",
    slide7_contact: "Let's Build Together",
  },
  ar: {
    title: "ملف BugMed Labs الاستثماري",
    subtitle: "إزالة مخاطر اكتشاف الأدوية باستخدام الذكاء الاصطناعي التوليدي",
    
    slide1_title: "المهمة: نموذج جديد للعلاجات",
    slide1_text: "بناء محرك اكتشاف علاجي هو الأكثر كفاءة في العالم ومدفوع بالبيانات، لتحويل الرؤى الحاسوبية إلى أدوية منقذة للحياة.",
    
    slide2_title: "المشكلة: \"وادي الموت\" في اكتشاف الأدوية",
    slide2_point1: "تكلفة ووقت هائلان: مليارات الدولارات وأكثر من عقد لكل دواء، بمعدل فشل يتجاوز 90%.",
    slide2_point2: "عنق زجاجة الفرضيات: نقطة الفشل الرئيسية ليست فقط التجارب السريرية؛ بل الفرضية البيولوجية الأولية التي غالبًا ما تكون معيبة.",
    slide2_point3: "فيضان البيانات، عجز في الرؤى: توجد مجموعات بيانات بيولوجية ضخمة، لكن تعقيدها يحجب المسارات العلاجية الجديدة.",

    slide3_title: "حلنا: محرك لتوليد الفرضيات",
    slide3_text1: "نحن لا نقوم فقط بفحص البيانات؛ بل نخلق المعرفة. منصة الذكاء الاصطناعي الخاصة بنا تستوعب بيانات بيولوجية معقدة ومتعددة الوسائط (جينوميات، بروتيوميات، بيانات سريرية) لتحديد الفجوات العلمية وتوليد فرضيات علاجية جديدة، قابلة للاختبار، ومدفوعة بالبيانات.",
    slide3_text2: "نحن نقدم أصولًا عالية القيمة ومُزالة المخاطر قبل إجراء تجربة واحدة في المختبر.",

    slide4_title: "التقنية: كيف تعمل",
    slide4_step1_title: "1. تكامل البيانات والرسم البياني المعرفي",
    slide4_step1_text: "نوحد مجموعات البيانات الضخمة والمعزولة في رسم بياني معرفي بيولوجي خاص بنا، ونرسم العلاقات المعقدة بين الجينات والبروتينات والأمراض والمركبات.",
    slide4_step2_title: "2. تحليل الفجوات بالذكاء الاصطناعي",
    slide4_step2_text: "تجتاز نماذجنا هذا الرسم البياني لتحديد 'المساحات البيضاء' - مناطق غير مستكشفة وروابط غير واضحة تمثل فرصًا علاجية غير مستغلة.",
    slide4_step3_title: "3. الفرضية التوليدية وإنشاء الأصول",
    slide4_step3_text: "يقوم المحرك بصياغة فرضية علاجية كاملة، بما في ذلك آلية العمل، والتحقق من الهدف، والتصميم الأولي للأصل. يصبح هذا أصلاً رقميًا تم التحقق منه مسبقًا.",

    slide5_title: "مثال على أصل أساسي: نظام للتعديل الموجه للبيئات الدقيقة للأنسجة المعادية",
    slide5_text: "ولّدت منصتنا نظامًا كاملاً، قيد الحصول على براءة اختراع، لتغيير البيئات الدقيقة للأنسجة المعادية بدقة. لهذا آثار عميقة لعلاج الأمراض المزمنة والمناعة الذاتية، مما يمثل برنامجًا عالي القيمة ومُزال المخاطر جاهزًا للشراكة.",
    slide5_link: "عرض دراسة الحالة",

    slide6_title: "نموذج عملنا: تكنولوجيا حيوية عالية الكفاءة في رأس المال وقيمة عالية",
    slide6_point1_title: "ملكية فكرية مولدة بالذكاء الاصطناعي",
    slide6_point1_text: "نقوم بإنشاء وتسجيل براءات اختراع لأصول علاجية جديدة تم إنشاؤها بواسطة منصتنا.",
    slide6_point2_title: "شراكات استراتيجية",
    slide6_point2_text: "نتشارك مع شركات الأدوية الرائدة وبناة المشاريع لتطوير أصولنا بشكل مشترك، ومشاركة المخاطر والمكافآت.",
    slide6_point3_title: "المنصة كخدمة",
    slide6_point3_text: "فرص مستقبلية لترخيص منصتنا لشركات الأدوية الكبرى لخطوط البحث والتطوير الداخلية الخاصة بهم.",

    slide7_title: "الفرصة: انضم إلينا في بناء المستقبل",
    slide7_text: "نسعى للحصول على استثمار في المرحلة الأولية (Seed) لإجراء التحقق في المختبر (in-vitro) لأصولنا الرائدة المولدة بالذكاء الاصطناعي. سيؤدي هذا إلى تحويل اكتشافاتنا الرقمية عالية القيمة إلى ملكية فكرية تم التحقق منها معمليًا، وجاهزة لصفقات ترخيص خارجية كبرى أو صفقات تطوير مشترك.",
    slide7_contact: "لنبدأ البناء معًا",
  }
};

const Slide = ({ title, children, icon: Icon }: { title: string, children: React.ReactNode, icon: React.ElementType }) => (
  <div className="min-h-[60vh] bg-secondary/30 rounded-lg p-8 md:p-12 border border-cyan-400/20 flex flex-col justify-center">
    <div className="flex items-center gap-4 mb-6">
      <div className="bg-cyan-400/10 p-3 rounded-full">
        <Icon className="h-8 w-8 text-cyan-400" />
      </div>
      <h2 className="text-3xl md:text-4xl font-bold text-cyan-400">{title}</h2>
    </div>
    <div className="space-y-4 text-lg text-neutral-300 md:pl-16">
      {children}
    </div>
  </div>
);

export default function DeckPage() {
  const { t } = useLanguage();
  const T = t(translations);

  return (
    <div className="bg-background text-foreground">
      <section className="py-20 md:py-32 pt-32 md:pt-48 text-center">
        <div className="container mx-auto px-4 md:px-6">
          <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold text-primary">{T.title}</h1>
          <p className="mt-4 text-lg md:text-xl text-neutral-300 max-w-3xl mx-auto">{T.subtitle}</p>
        </div>
      </section>

      <section className="pb-12 md:pb-16">
        <div className="container mx-auto px-4 md:px-6 space-y-16">
          
          <Slide title={T.slide1_title} icon={Target}>
            <p className="text-2xl italic">{T.slide1_text}</p>
          </Slide>
          
          <Slide title={T.slide2_title} icon={Microscope}>
            <ul className="list-disc list-inside space-y-3">
              <li>{T.slide2_point1}</li>
              <li>{T.slide2_point2}</li>
              <li>{T.slide2_point3}</li>
            </ul>
          </Slide>

          <Slide title={T.slide3_title} icon={BrainCircuit}>
            <p>{T.slide3_text1}</p>
            <p className="font-bold text-cyan-400/90">{T.slide3_text2}</p>
          </Slide>

          <Slide title={T.slide4_title} icon={Dna}>
             <div className="space-y-6">
                <div>
                  <h3 className="font-semibold text-neutral-100">{T.slide4_step1_title}</h3>
                  <p>{T.slide4_step1_text}</p>
                </div>
                 <div>
                  <h3 className="font-semibold text-neutral-100">{T.slide4_step2_title}</h3>
                  <p>{T.slide4_step2_text}</p>
                </div>
                 <div>
                  <h3 className="font-semibold text-neutral-100">{T.slide4_step3_title}</h3>
                  <p>{T.slide4_step3_text}</p>
                </div>
             </div>
          </Slide>

          <Slide title={T.slide5_title} icon={FileText}>
            <p>{T.slide5_text}</p>
            <div className="mt-4">
              <Button asChild variant="link" className="text-cyan-400 p-0 text-lg">
                <Link href="/case-studies">{T.slide5_link}</Link>
              </Button>
            </div>
          </Slide>

          <Slide title={T.slide6_title} icon={Handshake}>
            <div className="space-y-6">
                <div>
                  <h3 className="font-semibold text-neutral-100">{T.slide6_point1_title}</h3>
                  <p>{T.slide6_point1_text}</p>
                </div>
                 <div>
                  <h3 className="font-semibold text-neutral-100">{T.slide6_point2_title}</h3>
                  <p>{T.slide6_point2_text}</p>
                </div>
                 <div>
                  <h3 className="font-semibold text-neutral-100">{T.slide6_point3_title}</h3>
                  <p>{T.slide6_point3_text}</p>
                </div>
             </div>
          </Slide>

          <Slide title={T.slide7_title} icon={Rocket}>
            <p>{T.slide7_text}</p>
            <div className="mt-6">
                <Button asChild size="lg" className="bg-cyan-400 text-background hover:bg-cyan-500">
                    <Link href="/contact">{T.slide7_contact}</Link>
                </Button>
            </div>
          </Slide>

        </div>
      </section>
    </div>
  );
}

    